version: "2"
services:
   mongodb:
      image: mongo:latest
      container_name: my-mongodb-container
      ports:
        - 27017:27017
      volumes:
        - D:/mongodb:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=seymur
        - MONGO_INITDB_ROOT_PASSWORD=seymurpwd
   rabbitmq:
     image: rabbitmq:3.8-management-alpine
     container_name: 'rabbitmq'
     ports:
       - 5672:5672
       - 15672:15672
     volumes:
       - D:/rabbitmq/data/:/var/lib/rabbitmq/
       - D:/rabbitmq/log/:/var/log/rabbitmq
     networks:
      - rabbitmq-network
   keycloak:
     image: quay.io/keycloak/keycloak:18.0.2
     command:
       - start-dev
       - --import-realm
     ports:
       - "8085:8080"
     environment:
       - KEYCLOAK_ADMIN=admin
       - KEYCLOAK_ADMIN_PASSWORD=admin
     volumes:
       - D:/keycloak-config/:/opt/keycloak/data/import/
networks:
  rabbitmq-network:
    driver: bridge