server:
    port: 8084
spring:
    data:
        mongodb:
            authentication-database: admin
            database: joke_db
            host: localhost
            password: seymurpwd
            port: 27017
            username: seymur
    zipkin:
        base-url: http://localhost:9411
    application:
        name: bff
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8085/realms/my-realm
logging:
    level:
        root: info
